export const useLanguage = () => {
  const locale = useState<string>('locale', () => 'zh')

  const setLocale = (newLocale: string) => {
    locale.value = newLocale
  }

  const translations: Record<string, Record<string, string>> = {
    zh: {
      home: '首页',
      gallery: '图库',
      generator: '生成器',
      theme: '主题',
      language: '语言',
      randomCat: '随机猫咪',
      catGallery: '猫咪图库',
      catGenerator: '猫咪生成器',
      footerText: '基于 CATAAS API 构建',
      copyright: '版权所有 © 2024 - 保留所有权利',
      loading: '加载中...',
      error: '出错了',
      copySuccess: '复制成功',
      copyError: '复制失败',
      fetchCatError: '获取猫咪失败，请重试',
      imageLoadError: '图片加载失败，请重试',
      download: '下载',
      settings: '设置',
      filter: '筛选',
      tags: '标签',
      search: '搜索',
      close: '关闭',
      apply: '应用',
      reset: '重置',
      customText: '自定义文字',
      fontSize: '字体大小',
      fontColor: '字体颜色',
      filterEffect: '滤镜效果',
      none: '无',
      blur: '模糊',
      mono: '黑白',
      sepia: '复古',
      negative: '反色',
      paint: '油画',
      pixel: '像素化',
      width: '宽度',
      height: '高度',
      type: '类型',
      square: '正方形',
      medium: '中等',
      small: '小图',
      original: '原图',
      refresh: '刷新',
      copyLink: '复制链接',
      openInNewTab: '新窗口打开',
      totalCats: '猫咪总数',
      totalTags: '标签总数',
      apiEndpoints: 'API 端点',
      getRandomCat: '给我一只哈基米',
      clickToGetCat: '点击按钮获取随机猫咪',
      catsByTag: '按标签获取猫咪',
      selectTags: '选择标签',
      loadMore: '加载更多',
      noMoreData: '没有更多数据了',
      appTitle: '哈基米南北Look'
    },
    en: {
      home: 'Home',
      gallery: 'Gallery',
      generator: 'Generator',
      theme: 'Theme',
      language: 'Language',
      randomCat: 'Random Cat',
      catGallery: 'Cat Gallery',
      catGenerator: 'Cat Generator',
      footerText: 'Built with CATAAS API',
      copyright: 'Copyright © 2024 - All right reserved',
      loading: 'Loading...',
      error: 'Error',
      copySuccess: 'Copied successfully',
      copyError: 'Copy failed',
      fetchCatError: 'Failed to fetch cat, please try again',
      imageLoadError: 'Failed to load image, please try again',
      download: 'Download',
      settings: 'Settings',
      filter: 'Filter',
      tags: 'Tags',
      search: 'Search',
      close: 'Close',
      apply: 'Apply',
      reset: 'Reset',
      customText: 'Custom Text',
      fontSize: 'Font Size',
      fontColor: 'Font Color',
      filterEffect: 'Filter Effect',
      none: 'None',
      blur: 'Blur',
      mono: 'Mono',
      sepia: 'Sepia',
      negative: 'Negative',
      paint: 'Paint',
      pixel: 'Pixel',
      width: 'Width',
      height: 'Height',
      type: 'Type',
      square: 'Square',
      medium: 'Medium',
      small: 'Small',
      original: 'Original',
      refresh: 'Refresh',
      copyLink: 'Copy Link',
      openInNewTab: 'Open in New Tab',
      totalCats: 'Total Cats',
      totalTags: 'Total Tags',
      apiEndpoints: 'API Endpoints',
      getRandomCat: 'Get Random Cat',
      clickToGetCat: 'Click button to get a random cat',
      catsByTag: 'Get Cats by Tag',
      selectTags: 'Select Tags',
      loadMore: 'Load More',
      noMoreData: 'No more data',
      appTitle: 'Hajimi Look'
    }
  }

  const t = (key: string) => {
    return translations[locale.value]?.[key] || key
  }

  return {
    locale,
    setLocale,
    t
  }
}
